### ISSUE TITLE
Spike: Identify the best approach to collect cadet custom metadata (with respect to datahub's dbt ingestion)

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/find-moj-data#363]
### User Story

As a developer
I want the implemented approach in cadet for collection catalogue specific metadata to be the one best compatible with datahub
So that ingestion from cadet (via dbt datahub ingestion) works as simply as is possible

### Proposal

In a meeting with DMET members responsible for create-a-derived-table there were a couple of different approaches to collect catalogue specific metadata in cadet. This will need to be understood in a bit more detail following up with some or all of (Soumaya Mauthoor, Ben Waterfield, Jacob Hamblin-Pike, Phil Hall)

From memory the approaches were:
1. Use dbt groups to collect and organise some of these data
2. Use a model tagging strategy more wholly

Once clarity has been got for the above approaches we could try mock up some metadata to see how each integrates with the native datahub dbt ingestion

### Definition of Done

Example 
- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by seanprivett** [comment]
Session with CaDeT users to explore this further - where does it fit into their workflow
Is this just a PR we raise for them to approve
How do we build verification into CI/CD
Review metadata spec with CaDeT users
Where would you put the catalogue opt in flag

[This sheet](https://docs.google.com/presentation/d/1G_kPiM80Xa3V1HDxGQsyWnN1PcZYNufIva0pPZm0Lc0/edit#slide=id.g2686f9cf8d9_0_1915) shows the items highlighted in green which we are asking CaDeT users to enter manually. These should be the only metadata items we need to add into the workflow

**Comment by LavMatt** [comment]
I've spoken to Ben Waterfield re. the approaches and they're happy to be led by what is best for the catalogue ingestion (within reason for ease of implementation within cadet). So we need to figure out how well each integrates to present findings back the cadet guys. 

I agreed with Ben that we could create some tables in dbt to test the different approaches and integration with the datahub's dbt ingestion

**Comment by MatMoore** [comment]
Minimum metadata to integrate into the workflow:

- Owner
- Team contact
- Access requirements

https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=1846443805

We also need descriptions to be populated properly.

Based on previous spikes I *think* we should also include an explicit opt-in to indicate what should be visible to users of the service. 

Example of what this could look like in CaDeT:

```yaml
meta:
  visible_to_users: true
  owner_email: person@justice.gov.uk
  contact:
    - type: slack
      channel: '#abc'
  access_requirements: |
      Some markdown text
```

Things to explore

- [ ] Can we ingest metadata of this form and translate it into custom properties and tags?
- [ ] DBT groups????
- [ ] Can we dynamically apply the "well documented" tag or "needs documentation" etc based on missing metadata?
- [ ] Do we need to introduce additional checks into CaDeT workflows? What happens if the metadata is malformed?

**Comment by MatMoore** [comment]
Groups example looks like this

```
groups:
  - name: finance
    owner:
      # 'name' or 'email' is required; additional properties allowed
      email: finance@jaffleshop.com
      slack: finance-data
      github: finance-data-team
```

https://docs.getdbt.com/docs/build/groups

This conflates data owner/steward/custodian roles, and I'm not sure how this will be parsed by Datahub, so I'm not sure about this approach yet

Can try both groups and meta block approaches out though.

**Comment by MatMoore** [comment]
whereToAccessDataset - should be set to Analytical Platform

**Comment by MatMoore** [comment]
Existing groups: https://github.com/moj-analytical-services/create-a-derived-table/blob/d3999ee10bb63a160e8a14a41c8e2f5a3b1f746b/mojap_derived_tables/models/groups.yml#L4

These use slack IDs so we would need to translate that into human readable channels

**Comment by MatMoore** [comment]
Configs can be inherited in DBT, so perhaps we can apply them at the domain level

https://docs.getdbt.com/reference/configs-and-properties

**Comment by MatMoore** [comment]
Throwaway code for testing locally: https://github.com/moj-analytical-services/create-a-derived-table/compare/datahub-test

**Comment by MatMoore** [comment]
## Meta mapping findings

https://datahubproject.io/docs/generated/ingestion/sources/dbt/#dbt-meta-automated-mappings

### No nested matches
The DBT source's meta mapping config does not support matching nested properties, e.g. matching `contact.channel` here

```yaml
  contact:
    - type: slack
      channel: '#abc'
```

`OperationProcessor` has an arg for this `match_nested_props: bool = False`, but this was added for Kafka and not backported to DBT, see https://github.com/datahub-project/datahub/pull/8825

This can be worked around by not using nested yaml, e.g.

```yaml
slack_contact: '#abc'
teams_contact: '#def'
```

### Does not support custom properties
There is not an `add_property` mapping.

It might be worth looking into how much work this would be to add upstream.

### TODO: how does owner work?
There IS an add_owner.

- Does it create the user if it doesn't exist?
- Can it add an owner by email address or is this expecting URNs?

**Comment by MatMoore** [comment]
## Group findings

Group information doesn't seem to be picked up by datahub. It's not propagated to the custom properties, and datasets ingested with a group set do not have an owner.

This information is not present in the catalogue.json. It is in the manifest.json, but, I see no reference to "groups" in the code of the dbt ingestion source.

This seems like a dead end, and we will need to make use of `meta` and/or `tags` instead, even if it means duplicating some metadata 🙁

**Comment by MatMoore** [comment]
add_owner doesn't seem to work in my initial test so I need to debug this
- is the meta picked up correctly in dbt?
- does it matter where the meta is defined? (model vs group of models)
- does the owner ID need to match an existing owner?
- is it case sensitive?

**Comment by MatMoore** [comment]
https://datahubproject.io/docs/generated/ingestion/sources/dbt/#dbt-query_tag-automated-mappings might be useful for selectively mapping DBT tags to Datahub ones. I'm not sure how it interacts with the `tag_prefix` option

**Comment by MatMoore** [comment]
Maybe of interest - this can be used to enforce documentation coverage in dbt https://github.com/tnightengale/dbt-meta-testing

**Comment by MatMoore** [comment]
DBT docs is picking up the meta fields when they are in model files like `mojap_derived_tables/models/courts/common_platform_derived/common_platform_derived__all_offence_fct.yml`, but not within the `models` mapping in the `dbt_project.yaml`

I think I might need to do `+meta` instead of `meta`

**Comment by MatMoore** [comment]
## Update CaDeT task

Recommendation for `dbt_project.yaml`

```
    general:
      +meta:
        catalogue_slack_channel: '#data-engineering'
        #catalogue_teams_channel: '#data-engineering'
        #catalogue_owner_id: FirstName.LastName
```

- The owner ID is case sensitive - check it matches the URL of your datahub profile page
- If the owner has not logged into datahub, we will either hide the owner information, or only show an email (the name won't be available)
- We're assuming slack and teams are the two ways of communicating with a team
- The metadata can be set at any level of the DBT project structure (e.g. we can set it per domain)

Recommendation for model files

- Set `display_in_catalogue` tag for final models, including dimensions and fact tables
- Ignore staging tables
- Include common lookup tables in general

## Update ingestion recipe task

Add the following:

```yaml
    strip_user_ids_from_email: true
    tag_prefix: ""
    meta_mapping:
      owner_email:
        match: '.*'
        operation: 'add_owner'
        config:
          owner_type: user
          owner_category: DATAOWNER
```

TODO: this needs extending to handle custom properties.

**Comment by MatMoore** [comment]
Looking into what it would take to add a custom property operation to meta mapping.

There is already CustomPropertiesPatchHelper, exposed via DatasetPatchBuilder

metadata-ingestion/src/datahub/specific/custom_properties.py
metadata-ingestion/src/datahub/specific/dataset.py

We can use this to add a custom property without clearing existing ones.

If there is no match on the meta field, then intuitively we might expect the property to be removed. But there is no mechanism for this. (In our use case this wouldn't matter though)

OperationProcessor.process returns an aspect map - a dict mapping operation name to a resulting aspect definition

This is processed like this

```python
            meta_aspects: Dict[str, Any] = meta_aspects = action_processor.process(node.meta)

            aspects = self._generate_base_dbt_aspects(
                node, additional_custom_props_filtered, mce_platform, meta_aspects
            )

            dataset_snapshot = DatasetSnapshot(urn=node_datahub_urn, aspects=aspects)
            mce = MetadataChangeEvent(proposedSnapshot=dataset_snapshot)
            if self.config.write_semantics == "PATCH":
                mce = self.get_patched_mce(mce)

            yield MetadataWorkUnit(id=dataset_snapshot.urn, mce=mce)
```

`get_patched_mce` has cases for owners, tags, terms.

**Comment by MatMoore** [comment]
Two more configs I haven't tried

    enable_owner_extraction: bool = Field(
        default=True,
        description="When enabled, ownership info will be extracted from the dbt meta",
    )
    owner_extraction_pattern: Optional[str] = Field(
        default=None,
        description='Regex string to extract owner from the dbt node using the `(?P<name>...) syntax` of the [match object](https://docs.python.org/3/library/re.html#match-objects), where the group name must be `owner`. Examples: (1)`r"(?P<owner>(.*)): (\\w+) (\\w+)"` will extract `jdoe` as the owner from `"jdoe: John Doe"` (2) `r"@(?P<owner>(.*))"` will extract `alice` as the owner from `"@alice"`.',
    )

This is overwritten by meta mapping in `_aggregate_owners`. I think we're better off using our own meta property though because CaDeT currently users owners to refer to something more akin to a data custodian or technical owner. Whereas we want to capture a named individual who will be the business owner.

**Comment by MatMoore** [comment]
What does the add_owner meta mapping actually do?

It creates the following aspect:

```python
owner_aspect = OwnershipClass(
                owners=[
                    OwnerClass(
                        owner=x.get("urn"),
                        type=x.get("category"),
                        typeUrn=x.get("categoryUrn"),
                        source=(
                            OwnershipSourceClass(type=self.owner_source_type)
                            if self.owner_source_type
                            else None
                        ),
                    )
                    for x in sorted(
                        operation_map[Constants.ADD_OWNER_OPERATION],
                        key=lambda x: x["urn"],
                    )
                ]
            )
```

There's another example here that works in a similar way https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/examples/library/dataset_add_owner.py

**Comment by MatMoore** [comment]
How slack linking works

https://api.slack.com/docs/deep-linking

Either we ask for the name and redirect like so
https://api.slack.com/reference/deep-linking#app_channel

Or we ask for the name and ID and generate a slack:// link
https://api.slack.com/reference/deep-linking#open_a_channel

I think the latter assumes the user has a slack client installed, so the former would be more reliable

Teams does let you export a channel link but I don't think people can just drop into channels like they can on slack(?) Need to double check what we want in this case.

**Comment by MatMoore** [comment]
Next steps: write up a runbook page documenting how this should be captured, then do a final check the metadata comes through as expected.

**Comment by MatMoore** [comment]
Runbook PR: https://github.com/ministryofjustice/data-catalogue-runbooks/pull/31

And this is a draft PR to add some initial metadata: https://github.com/moj-analytical-services/create-a-derived-table/pull/1568/files

Before merging that we will need to speak to the data engineers and
- Populate the owners for each domain
- Make sure the owner exists in datahub
- Review the models (and sources?) tagged with `dc_display_in_catalogue` to make sure we're making the right stuff visible/not visible
