### ISSUE TITLE
🚀  EPIC: Deploy to prod

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#494]
### Brief summary of what this Epic is

Set up the production environment so our first beta users can start using it!

### List of issues in this epic

- [ ] Creation of prod environment for Find MOJ data
- [ ] EntraID for prod
- [ ] Deployment into prod environments
- [x] https://github.com/ministryofjustice/find-moj-data/issues/493
- [ ] Create deployment notifications. Spike? Just Slack for now until / if we get a Teams channel to notify DIP team.
