### ISSUE TITLE
Optimal search behaviour

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/find-moj-data#877]
### Context
Recent changes to the Datahub search behaviour have highlighted the need for control to ensure we retain the ability to provide users with an optimal search experience.

We have enabled a custom search [configuration](https://github.com/ministryofjustice/data-catalogue/blob/af1abd4d2abdf991701682c87a35fc1066489f21/helm_deploy/values-base.yaml#L419) by overriding the base helm values. This provides a way to identify query strings through the use of regex and apply different treatments accordingly.

Search is big subject area and there will no doubt be changes that we would want to make further down the line, the aim of this ticket is to get perspectives within the team around the current behaviour with a view to adding to our configuration over time.

### Documentation
- Datahub custom [search](https://datahubproject.io/docs/how/search/#customizing-search)
- Elastic search simple [query](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-simple-query-string-query.html)
- Elastic search match phrase prefix [query](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-match-query-phrase-prefix.html)
- Elastic search exact term [query](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-term-query.html)

### Sub-optimal behaviour

- Quoted searches and those containing underscores are identified by the same regular expression and are treated as exact matches. This means that you would need to enter the entire entity name  `price_paid_monthly_latest` to return this result, `price_paid` would yield no results.

```
- queryRegex: >-
    ^["'].+["']$|^[a-zA-Z0-9]\S+[_.-]\S+[a-zA-Z0-9]$
    simpleQuery: false
    prefixMatchQuery: false
    exactMatchQuery: true
    functionScore:
      functions:
        - filter:
            term:
              deprecated:
                value: true
          weight: 0.25
      score_mode: multiply
      boost_mode: multiply
```

### Example
Example - simple search
![Image](https://github.com/user-attachments/assets/85f86b28-14c0-4ee0-911c-9fedd4b387bf)

Example - partial asset name with underscores
![Image](https://github.com/user-attachments/assets/22226f2e-4770-42bb-9b4d-2f7eb4ed3a21)

Example - full asset name with underscores
![Image](https://github.com/user-attachments/assets/f40a6631-969d-47bf-a3c3-0514097ba4d2)

Implementing `prefixMatchQuery: true` will return partial matches. [Ref](https://github.com/datahub-project/datahub/issues/11398#issuecomment-2365323473)

### Questions
- [ ] Do we want the ability to handle quoted queries and those containing underscores separately?
- [ ] Do we want to support prefix matching which will enable partial results to be returned

### Todo
- [x] Explore options to adapt custom search behaviour to suit our needs
- [x] Discuss at the monthly architecture meeting
